import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
      <video loading="lazy" muted="muted" src="https://cdnl.iconscout.com/lottie/premium/thumb/man-help-woman-for-pregnancy-exercise-4054967-3379620.mp4" type="video/mp4" autoplay="autoplay" loop="loop"></video>


      <picture class="thumb_PdMgf"><img src="https://cdn3d.iconscout.com/3d/premium/thumb/ramen-noodles-4604426-3815462.png" alt="Ramen Noodles 3D Illustration" loading="lazy"/></picture>

    </div>
  )
}
